### PR TITLE
Add consumer interface to CompletableCompletionStage

### PR DESCRIPTION
**Pull request by lukiano**
So that it can be added to whenComplete().. etc without anonymous lambda functions

### CODE REVIEW

**Comment by lukas-krecan-gdc** [comment]
Thanks, it's an interesting idea. Can you please add some JavaDoc? And just to satisfy my curiosity, may please shortly describe your use case? (an example would be great)

**Comment by lukiano** [comment]
I added more javadoc. A use case for the BiConsumer is to use it as a target of the whenComplete operation:

    CompletionStage<X> someComplettionStage = ...
    CompletableCompletionStage<X> ccs = completionStageFactory.createCompletionStage();
    someCompletionStage.whenComplete(ccs); // ccs will be completed with the same result (success or failure) as someCompletionStage

**Comment by lukas-krecan** [comment]
I have been thinking about it extension of Consumer and BiConsumer feels confusing. It may be caused by my lack of experience when designing Java 8 APIs. In my opinion something like this 5f9242082e1bfb8e04ca531640117d365246ae43 makes more sense. You have to use method references, but I find it less confusing. What do you think?

**Comment by lukiano** [comment]
Yes, method references is fine. I think you don't need for them to return void, the ones that return boolean should work fine. Have you tried them? The one I'd be interested in this case is void doComplete(T result, Throwable throwable)

**Comment by lukas-krecan** [comment]
Unfortunately the methods have to return void, otherwise their signature does not match Consumer interface. I will close this pull request and merge and release my changes. Thanks a lot for the idea.

**Pull request closed without merging**
